apiVersion: v1
kind: Pod
metadata:
  name: policy-test
  namespace: saleor1
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
         drop:
           - ALL

