apiVersion: v1
kind: Pod
metadata:
    name: qos-besteffort
    namespace: resource-lab
spec:
  containers:
    - name: app1
      image: nginx:latest 

---
apiVersion: v1
kind: Pod
metadata:
  name: qos-brustable
  namespace: resource-lab
spec:
  containers:
    - name: app2
      image: nginx:latest
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed
  namespace: resource-lab
spec:
  containers:
    - name: app3
      image: nginx:latest
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"

      
