apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  namespace: {{ .Values.api.ns }}
spec:
  type: {{ .Values.api.service.type }}
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4    #this will be the primary IP for that service
  #  - IPv6
  selector:
    app: api
  ports:
    - name: {{ .Values.api.ports.name }}
      port: {{ .Values.api.ports.port  }}
      targetPort: {{ .Values.api.ports.port }}



