apiVersion: v1
kind: Service
metadata:
  name: {{.Values.postgres.service.name}}
  namespace: {{ .Values.postgres.ns }}
spec:
  clusterIP: {{ .Values.postgres.service.type }}
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: {{ .Values.postgres.app }}
  ports:

    - name: {{ .Values.postgres.ports.name }}
      port: {{ .Values.postgres.ports.port }}
      targetPort: {{ .Values.postgres.ports.port }}


