apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.env.secret_file }}
  namespace: saleor1
type: Opaque

stringData:
  DATABASE_URL: 'postgres://saleor:AppSecrets@postgres:5432/saleor'
  Redis_URL: 'redis://redis:6379/0'

immutable: true
