apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: abdul-dev-binding
  namespace: saleor1
subjects:
  - kind: User
    name: abdul-dev
roleRef:
  kind: Role
  name: saleor-developer

