apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: saleor-viewer
  namespace: saleor1
rules:
  - apiGroups: [""]
    resources:
      - pod
      - services
      - configmaps
    verbs:
      - get 
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch

