apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: saleor-deployment-operator
  namespace: saleor1

rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
 
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: saleor-deployment-operator
  namespace: saleor1
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: saleor-deployment-operator-binding
  namespace: saleor1
subjects:
  - kind: ServiceAccount
    name: saleor-deployment-operator
    namespace: saleor1
roleRef:
    kind: Role
    name: saleor-deployment-operator
    apiGroup: rbac.authorization.k8s.io
