apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.env.secret_file }}
  namespace: {{ .Values.postgres.ns }}        #because secrets should be scoped with the namespace of the pod or any object

type: Opaque
stringData:
   POSTGRES_DB: "saleor"
   POSTGRES_USER: "saleor"
   POSTGRES_PASSWORD: "AppSecrets"
