name: ci-saleor
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths-ignore:
      - "kind_cluster/k8s/values.yaml"
  pull_request:
    branches:
      - main
permissions:
  contents: read    # good for applying the least privileges rule
jobs:
  backend-test:
    name: Backend tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: saleor
          POSTGRES_USER: saleor
          POSTGRES_PASSWORD: AppSecrets
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U saleor -d saleor"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >- 
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    defaults:
        run: 
          working-directory: saleor-backend
    steps:
        - name: Checkout repository
          uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
          with:
            enable-cache: true
        - name: Set up Python
          run: uv python install 3.12
        - name: install dependencies
          run: uv sync --locked 
        - name: Ruff format check
          run: uv run ruff format .
        #- name: Run backend tests
         # env:
          # DATABASE_URL: postgres://saleor:AppSecrets@127.0.0.1:5432/saleor
           #REDIS_URL: redis://127.0.0.1:6379/0
          #run: uv run pytest --reuse-db
  dashboard-test:
    name: dashboard-test
    needs:
      - backend-test
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: saleor-dashboard
    steps:
      - name: checkout repository
        uses:  actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: Set up pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413
        with:
          version: 11.13.1
      - name: Set up Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: saleor-dashboard/pnpm-lock.yaml
      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile
      # - name: Lint
      #   run: pnpm run lint
      # - name: Format check
      #   run: pnpm run format:check
      # - name: Type check
      #   run: pnpm run check-types
      # - name: Run tests
      #   run: pnpm run test:ci
      # - name: Build dashboard
      #   run: pnpm run build 
  docker-build:
    name: Build and push docker images.
    needs:
      - backend-test
      - dashboard-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@vf87e5991a6d7451dcb8d9637bfbc97413f497069
      - name: Login to Docker hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          username: ${{ secrets.DockerHub_username }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push Saleor API image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          context: ./saleor-backend
          file: ./saleor-backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/saleor-api:${{ github.ref_name }}
      - name: Build and Push Saleor dashboard image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          context: ./saleor-dashboard
          file: ./saleor-dashboard/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/saleor-dash:${{ github.ref_name }}


